### ISSUE TITLE
rename extension to something specific to copilot extensions?

### ISSUE THREAD

**Issue by gr2m** [copilot-extensions/gh-debug-cli#1]
Naming is hard™ 

I think we should consider to

1. remove the `-cli` suffix of the extension name. It's not needed because we are already in a CLI environment
2. replace the generic "debug" to something like "copilot-extension-debug"

When in doubt, I vote for clarity > brevity

It will be easier to rename it before we go to public beta

**Comment by Anillote** [comment]
https://www.instagram.com/unde_sanu_2008?igsh=MWRxZGoyc2c2am1ucQ==
